import { test, expect } from "@playwright/test";
test("demo navigates all tabs and recalculates a priced plan", async ({ page }, testInfo) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "What can we make today?" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("planner.png"), fullPage: true });
  await page.getByRole("button", { name: "Find compatible meals" }).click();
  await expect(page.getByRole("region", { name: "Compatible recipes" })).toBeVisible();
  await page.getByRole("button", { name: "Build my week" }).click();
  await expect(page.getByRole("heading", { name: "Your seven-day draft" })).toBeVisible();
  await expect(page.locator(".planned-meal")).toHaveCount(14);
  await expect(page.getByRole("heading", { name: "Your shopping list" })).toBeVisible();
  await page.locator('select[aria-label="Swap Monday dinner"]').selectOption("bean-corn-salad");
  await expect(page.getByRole("status")).toContainText("recalculated");
  await page.getByRole("button", { name: "Home", exact: true }).click();
  await page.getByLabel("peanut", { exact: true }).check();
  await page.getByRole("button", { name: "Meals", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Your seven-day draft" })).toHaveCount(0);
  await page.getByRole("button", { name: "Find compatible meals" }).click();
  await expect(page.getByRole("heading", { name: "Banana and peanut butter bread" })).toHaveCount(0);
  await page.getByRole("button", { name: "Learn", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Start with the basics" })).toBeVisible();
  await page.getByRole("button", { name: "Help", exact: true }).click();
  await expect(page.getByRole("link", { name: "Call 211" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
test("keyboard navigation and age-appropriate optional BMI", async ({ page }) => {
  await page.goto("/");
  await page.keyboard.press("Tab");
  await expect(page.getByRole("link", { name: "Skip to content" })).toBeFocused();
  await page.getByRole("button", { name: "Home", exact: true }).click();
  await page.getByLabel("Hide BMI and weight content").uncheck();
  await page.getByText("Optional BMI screening", { exact: true }).click();
  await page.getByRole("combobox", { name: "Age group", exact: true }).selectOption("teen");
  await expect(page.getByRole("link", { name: "Use CDC’s child and teen calculator" })).toBeVisible();
  await expect(page.getByLabel("Weight (kg)")).toHaveCount(0);
  await page.getByRole("combobox", { name: "Age group", exact: true }).selectOption("infant");
  await expect(page.getByText("BMI calculators are not used for children under 2.")).toBeVisible();
});
test('My food settings persist locally and gate unresolved allergies', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await page.getByRole('button', { name: /My food Tell us/ }).click();
  await expect(page.getByRole('tab', { name: 'Diet' })).toHaveAttribute('aria-selected','true');
  await page.getByRole('tab', { name: 'Diet' }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('tab', { name: 'Allergies' })).toBeFocused();
  await expect(page.getByRole('tab', { name: 'Allergies' })).toHaveAttribute('aria-selected','true');
  await page.getByRole('button', { name: 'With a grown-up' }).click();
  await page.getByRole('tab', { name: 'Diet' }).click();
  await page.getByRole('button', { name: 'No pork' }).click();
  await page.getByRole('tab', { name: 'Allergies' }).click();
  await page.getByLabel('Food allergy').fill('groundnuts, nuts');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.getByText('Does this mean peanut?')).toBeVisible();
  await expect(page.getByText('Needs checking — please clarify this food.')).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await page.getByRole('button', { name: /My food Tell us/ }).click();
  await page.getByRole('tab', { name: 'Allergies' }).click();
  await expect(page.getByText('groundnuts', { exact: true })).toBeVisible();
});
test('My food tabs remain readable at 360 pixels and simulated 200 percent zoom', async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 900 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await page.getByRole('button', { name: /My food Tell us/ }).click();
  await page.evaluate(() => { document.documentElement.style.zoom = '2'; });
  await expect(page.getByRole('tab', { name: 'Allergies' })).toBeVisible();
  await expect(page.getByRole('tab', { name: 'Nutrients' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
});
