'use client';
import { useState, type FormEvent, type KeyboardEvent } from 'react';
import type { HouseholdProfile, MemberFoodSettings, FoodRule, NutrientInterest } from '@/lib/domain';
import { newMember, proposeAllergies } from '@/lib/food-settings';
import { foodNameTags } from '@/lib/ingredient-relationships';

const sections = ['Diet', 'Allergies', 'Favorites', 'Nutrients'] as const;
const rules: { title: string; values: [FoodRule, string][] }[] = [
  { title: 'How we eat', values: [['vegetarian','🥬 Vegetarian'],['vegan','🌱 Vegan'],['pescatarian','🐟 Pescatarian']] },
  { title: 'Foods we avoid', values: [['exclude_beef','🐄 No beef'],['exclude_pork','🐖 No pork'],['gluten_free','🌾 Gluten-free'],['dairy_free','🥛 Dairy-free']] },
  { title: 'Health needs — with a grown-up', values: [['type_1_diabetes','Type 1 diabetes'],['type_2_diabetes','Type 2 diabetes'],['celiac','Celiac disease']] },
];
const nutrients: [NutrientInterest['nutrientId'], string][] = [['protein','Protein'],['iron','Iron'],['potassium','Potassium'],['fiber','Fiber'],['vitamin_d','Vitamin D'],['vitamin_b12','Vitamin B12']];
const split = (value: string) => value.split(',').map(v => v.trim()).filter(Boolean).slice(0, 30);

export function MyFood({ profile, updateProfile, back, onSave, onChildView }: { profile: HouseholdProfile; updateProfile: (update: Partial<HouseholdProfile>) => void; back: () => void; onSave?: (profile: HouseholdProfile) => Promise<void>; onChildView?: () => void }) {
  const [section, setSection] = useState<(typeof sections)[number]>('Diet');
  const [memberId, setMemberId] = useState(profile.members?.[0]?.id ?? 'member-1');
  const [caregiver, setCaregiver] = useState(false);
  const [saveStatus, setSaveStatus] = useState('');
  const [entry, setEntry] = useState('');
  const [draft, setDraft] = useState<Record<string,string>>({});
  const members = profile.members?.length ? profile.members : [newMember('member-1','Me')];
  const member = members.find(m => m.id === memberId) ?? members[0];
  const favoriteConflict = member.likes.some(name => { const tags = foodNameTags(name); return member.rules.includes('dairy_free') && tags.includes('dairy') || member.rules.includes('exclude_beef') && tags.includes('beef') || member.rules.includes('exclude_pork') && tags.includes('pork') || (member.rules.includes('celiac') || member.rules.includes('gluten_free')) && tags.includes('gluten'); });
  function saveMember(changes: Partial<MemberFoodSettings>) { updateProfile({ members: members.map(m => m.id === member.id ? { ...m, ...changes } : m) }); setSaveStatus(''); }
  function addMember() { const next = newMember(`member-${crypto.randomUUID()}`, `Family member ${members.length + 1}`); updateProfile({ members: [...members, next] }); setMemberId(next.id); }
  function changeRule(rule: FoodRule) { saveMember({ rules: member.rules.includes(rule) ? member.rules.filter(r => r !== rule) : [...member.rules, rule] }); }
  function addAllergies(event: FormEvent) { event.preventDefault(); const proposals = proposeAllergies(entry); if (!proposals.length) return; saveMember({ allergies: [...member.allergies, ...proposals], noKnownAllergies: false }); setEntry(''); }
  function confirmAllergy(index: number) { const selected = member.allergies[index]; if (!selected?.canonicalId) return; const existing = member.allergies.findIndex((item,i) => i !== index && item.status === 'confirmed' && item.canonicalId === selected.canonicalId); const kept = existing >= 0 ? existing : index; saveMember({ allergies: member.allergies.filter((item,i) => i === kept || item.canonicalId !== selected.canonicalId).map(item => item === member.allergies[kept] ? { ...item, status: 'confirmed' } : item) }); }
  function tabKey(event: KeyboardEvent<HTMLButtonElement>, index: number) { let next = index; if (event.key === 'ArrowRight') next = (index + 1) % sections.length; else if (event.key === 'ArrowLeft') next = (index - 1 + sections.length) % sections.length; else if (event.key === 'Home') next = 0; else if (event.key === 'End') next = sections.length - 1; else return; event.preventDefault(); setSection(sections[next]); document.getElementById(`food-tab-${sections[next]}`)?.focus(); }
  function listInput(key: 'likes' | 'dislikes' | 'cuisines' | 'otherExclusions', label: string) { return <div className="list-input"><label>{label}<input value={draft[key] ?? ''} onChange={e => setDraft(d => ({ ...d, [key]: e.target.value }))} placeholder="Type a food, or several separated by commas" /></label><button type="button" className="button secondary" onClick={() => { saveMember({ [key]: [...member[key], ...split(draft[key] ?? '')].slice(0,30) }); setDraft(d => ({ ...d, [key]: '' })); }}>Add</button><div className="chips">{member[key].map((item,i) => <span className="saved-chip" key={`${item}-${i}`}>{item} <button type="button" aria-label={`Remove ${item}`} onClick={() => saveMember({ [key]: member[key].filter((_,j) => j !== i) })}>Remove</button></span>)}</div></div>; }
  return <section className="my-food">
    <button className="text-button" onClick={back}>← Back</button><div className="page-heading"><span className="eyebrow">My food</span><h1>Foods that work for you</h1><p>Tell us what works for you. Your choices help find meal ideas.</p></div>
    <div className="panel food-member"><label>{caregiver ? 'Whose food settings?' : 'Your food settings'}<select value={member.id} onChange={e => setMemberId(e.target.value)} disabled={!caregiver}>{members.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><button className="button secondary" onClick={() => { if (caregiver) { setMemberId(members[0].id); onChildView?.(); } setCaregiver(v => !v); }}>{caregiver ? (onChildView ? 'Child view and sign out' : 'Child view') : 'With a grown-up'}</button>{caregiver && <><label>Member name<input maxLength={60} value={member.name} onChange={e => saveMember({ name: e.target.value || 'Member' })} /></label><label>Age group<select value={member.ageGroup ?? "child"} onChange={e => saveMember({ ageGroup: e.target.value as MemberFoodSettings["ageGroup"] })}><option value="child">Child</option><option value="teen">Teen</option><option value="adult">Adult</option></select></label><button className="text-button" onClick={addMember}>Add family member</button><p className="notice">This prototype has no account sign-in. The grown-up view is a display choice, not verified caregiver authorization.</p></>}</div>
    <div className="food-tabs" role="tablist" aria-label="Food settings">{sections.map((name,index) => <button role="tab" id={`food-tab-${name}`} aria-controls={`food-panel-${name}`} aria-selected={section === name} tabIndex={section === name ? 0 : -1} className={section === name ? 'selected' : ''} key={name} onKeyDown={event => tabKey(event,index)} onClick={() => setSection(name)}>{name}</button>)}</div>
    <div className="panel food-panel" role="tabpanel" id={`food-panel-${section}`} aria-labelledby={`food-tab-${section}`}>
      {section === 'Diet' && <><h2>Foods that work for you</h2>{rules.filter(group => caregiver || !group.title.startsWith('Health needs')).map(group => <fieldset key={group.title}><legend>{group.title}</legend><div className="choice-grid">{group.values.map(([key,label]) => <button type="button" key={key} className={member.rules.includes(key) ? 'choice selected' : 'choice'} aria-pressed={member.rules.includes(key)} onClick={() => changeRule(key)}>{label}</button>)}</div></fieldset>)}{listInput('otherExclusions','Other foods we avoid')}{caregiver && <><div className="form-grid"><label>Are eggs okay?<select value={String(member.eggAllowed)} onChange={e => saveMember({ eggAllowed: e.target.value === 'null' ? null : e.target.value === 'true' })}><option value="null">Ask later</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Is dairy okay?<select value={String(member.dairyAllowed)} onChange={e => saveMember({ dairyAllowed: e.target.value === 'null' ? null : e.target.value === 'true' })}><option value="null">Ask later</option><option value="true">Yes</option><option value="false">No</option></select></label></div><label className="check-line"><input type="checkbox" checked={!!member.medicalConsent} onChange={e => saveMember({ medicalConsent: e.target.checked })} />I agree to save this member's health settings in a connected caregiver account.</label><label>Existing clinician instructions (caregiver-reported)<textarea maxLength={1000} value={member.clinicianInstructions} onChange={e => saveMember({ clinicianInstructions: e.target.value })} /></label></>}<p className="muted">Celiac needs product label and preparation checks. Diabetes meal planning follows the person's care team; this app does not calculate insulin or set carbohydrate targets.</p>{caregiver && member.rules.some(rule => rule === "type_1_diabetes" || rule === "type_2_diabetes") && <p className="notice">Carbohydrate estimates: unknown for the demo recipes. Verified ingredient records and measured amounts are needed.</p>}</>}
      {section === 'Allergies' && <><h2>Foods to avoid</h2><p>Type an allergy, then tap Add. A grown-up can help check it.</p>{caregiver ? <form onSubmit={addAllergies} className="inline-form"><label>Food allergy<input value={entry} maxLength={500} onChange={e => setEntry(e.target.value)} placeholder="peanuts, milk, sesame" /></label><button className="button" type="submit">Add</button></form> : <p className="notice">Ask a grown-up to add or check allergies.</p>}<div className="allergy-list">{profile.allergies.length > 0 && <p className="notice">Existing household allergies also apply to shared meals: {profile.allergies.join(", ")}. Change them in Family settings.</p>}{member.allergies.map((item,i) => <div className="saved-chip" key={`${item.rawText}-${i}`}><strong>{item.rawText}</strong><span>{item.canonicalId ? `Does this mean ${item.canonicalId}?` : 'Needs checking — please clarify this food.'}</span><small>{item.status.replaceAll('_',' ')}</small>{caregiver && <div className="actions">{item.canonicalId && item.status !== 'confirmed' && <button className="button secondary" onClick={() => confirmAllergy(i)}>Confirm mapping</button>}<button className="text-button" onClick={() => setEntry(item.rawText)}>Edit</button><button className="text-button" onClick={() => saveMember({ allergies: member.allergies.filter((_,j) => j !== i) })}>Remove</button></div>}</div>)}</div>{caregiver && <label className="check-line"><input type="checkbox" checked={member.noKnownAllergies} onChange={e => saveMember({ noKnownAllergies: e.target.checked, allergies: e.target.checked ? [] : member.allergies })} />No known food allergies</label>}{!member.noKnownAllergies && !member.allergies.length && <p className="notice">Allergies have not been answered yet.</p>}<p className="muted">Unconfirmed or unclear allergies pause personalized meal suggestions. Check product labels and cross-contact with a caregiver.</p></>}
      {section === 'Favorites' && <><h2>Foods you like</h2><p>What foods do you enjoy? You can change these anytime.</p>{favoriteConflict && <p className="notice">Let's find a version that works with your food settings.</p>}{listInput('likes','Foods I like')}{listInput('dislikes',"Foods I'd rather skip")}{listInput('cuisines','Favorite meals or cuisines')}<fieldset><legend>Favorite flavors</legend><div className="choice-grid">{['mild','spicy','savory','sweet'].map(value => <button className={member.flavors.includes(value) ? 'choice selected' : 'choice'} aria-pressed={member.flavors.includes(value)} key={value} onClick={() => saveMember({ flavors: member.flavors.includes(value) ? member.flavors.filter(x => x !== value) : [...member.flavors,value] })}>{value}</button>)}</div></fieldset><fieldset><legend>Favorite textures</legend><div className="choice-grid">{['crunchy','soft','smooth'].map(value => <button className={member.textures.includes(value) ? 'choice selected' : 'choice'} aria-pressed={member.textures.includes(value)} key={value} onClick={() => saveMember({ textures: member.textures.includes(value) ? member.textures.filter(x => x !== value) : [...member.textures,value] })}>{value}</button>)}</div></fieldset>{caregiver && <><div className="form-grid"><label>Where we shop<input maxLength={80} value={profile.preferredStoreName ?? ''} onChange={e => updateProfile({ preferredStoreName: e.target.value })} /></label><label>Store location<input maxLength={80} value={profile.preferredStoreLocation ?? ''} onChange={e => updateProfile({ preferredStoreLocation: e.target.value })} /></label></div><small>Prices still use the demo price list until a store connection is available.</small></>}<label>Other preferences<textarea maxLength={500} value={member.note} onChange={e => saveMember({ note: e.target.value })} /></label></>}
      {section === 'Nutrients' && <><h2>Foods to explore</h2><p>Let's explore foods with helpful nutrients. These choices are interests, not diagnoses.</p>{nutrients.map(([id,label]) => { const selected = member.nutrients.find(n => n.nutrientId === id);  return <div className="nutrient-row" key={id}><label className="check-line"><input type="checkbox" checked={!!selected} onChange={e => saveMember({ nutrients: e.target.checked ? [...member.nutrients, { nutrientId: id, reason: 'food_ideas', caregiverReported: false, reviewStatus: 'pending_confirmation' }] : member.nutrients.filter(n => n.nutrientId !== id) })} />{label}</label>{selected && <><label>Why are you exploring {label.toLowerCase()}?<select value={selected.reason} onChange={e => saveMember({ nutrients: member.nutrients.map(n => n.nutrientId === id ? { ...n, reason: e.target.value as NutrientInterest['reason'], caregiverReported: e.target.value === 'clinician_recommended' } : n) })}><option value="food_ideas">I'd like more food ideas</option>{caregiver && <option value="clinician_recommended">A clinician recommended this (caregiver-reported)</option>}<option value="unsure">I'm not sure</option></select></label><p className="muted">Reviewed food examples are not yet available in this demo.</p></>}{id === 'potassium' && selected && caregiver && <label>Potassium care check<select value={member.potassiumCheck} onChange={e => saveMember({ potassiumCheck: e.target.value as MemberFoodSettings['potassiumCheck'] })}><option value="unknown">Unsure — hold personalized ideas</option><option value="no_restriction_reported">No restriction reported; review with care team</option><option value="clinician_recommended">Existing clinician recommendation reported</option></select></label>}</div>; })}<p className="notice">Food ideas cannot diagnose or correct a low level. Nutrient amounts are unknown until product or USDA records are verified.</p></>}
    </div><button className="button" onClick={async () => { try { if (onSave) await onSave({ ...profile, members }); setSaveStatus('Saved!'); } catch (error) { setSaveStatus(error instanceof Error ? error.message : 'Could not save.'); } }}>Save</button><p role="status" className="saved-note">{saveStatus || (onSave ? 'Sign in as a caregiver to save across devices.' : 'Settings save in this browser. Meal ideas refresh when settings change.')}</p>
  </section>;
}
